name: Site

on:
    workflow_dispatch:
    push:
        branches:
            - site

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.16.0
              uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Installing dependencies...
              run: npm install -D

            - name: Building site...
              run: npm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: dist
